spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cursa4}
    username: ${SPRING_DATASOURCE_USERNAME:eoeqs}
    password: ${SPRING_DATASOURCE_PASSWORD:eoeqs}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      connection-timeout: 30000
      initialization-fail-timeout: -1
      connection-test-query: SELECT 1
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    connect-retries: 10
    connect-retries-interval: 5

  jwt:
    secret-key:
    expiration: 360000000000
  mail:
    host: smtp.yandex.ru
    port: 587
    username: stmp@yandex.ru
    password: 111
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.yandex.ru
minio:
  url: ${MINIO_URL:http://localhost:9000}
  access:
    name: ${MINIO_ACCESS_NAME:fergoeqs}
    secret: ${MINIO_ACCESS_SECRET:fergoeqs123456789}
    bucket:
      name: vetcare

#logging:
#  level:
#    org:
#      springframework: trace
